name: Deploy

on:
  push:
    branches: [prod]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: docker.pkg.github.com/tribecamp/discord-bot/discord-bot
          tag_with_ref: true
